name: check

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - uses: Kesin11/actions-timeline@v2
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: install packages
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm test
      - name: build
        run: npm run build
